version: "3"

services: 
  trainer:
    build: 
        context: ./trainer/
        dockerfile: Dockerfile
    volumes: 
        - "./:/app"
    ports:
      - 8899:8888
    command: bash -c "pip install -e /app/trainer/ &&
      jupyter lab --ServerApp.token=justatokengesture --ip=0.0.0.0 --port=8888 --no-browser --allow-root"
  api:
    build: 
        context: ./api/
        dockerfile: Dockerfile
    ports:
        - 3007:80
    volumes: 
        - "./api/:/api/"
        - "./data/:/data"
        - "./models/:/models"
    command: bash -c "ls -al && uvicorn --reload --host 0.0.0.0 --port 80 --log-level info --lifespan on --forwarded-allow-ips='*' 'app.main:app'"