version: "3"

services: 
  trainer:
    build: 
        context: ./trainer/
        dockerfile: Dockerfile
    volumes: 
        - "./:/app"
    ports:
      - 8899:8888
    command: bash -c "pip install -e /app/trainer/ &&
      jupyter lab --ServerApp.token=justatokengesture --ip=0.0.0.0 --port=8888 --no-browser --allow-root"
  # postgres:
  #   image: postgis/postgis
  #   environment: 
  #     - POSTGRES_DB=car_insurance
  #     - POSTGRES_PASSWORD=mysecretpassword
  #   volumes:
  #     - ./data/postgres-data:/var/lib/postgresql/data
  # pg_admin:
  #   image: dpage/pgadmin4
  #   environment: 
  #     - PGADMIN_DEFAULT_EMAIL=user@domain.local
  #     - PGADMIN_DEFAULT_PASSWORD=SuperSecret
  #   ports:
  #     - 81:80
  api:
    build: 
        context: ./api
        dockerfile: Dockerfile
    ports:
        - 3002:80
    volumes: 
        - "./:/app"
    command: /start-reload.sh